# fly.toml app configuration file generated for prakalight-api on 2023-06-15T01:40:51+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prakalight-api"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
